import 'dart:io' show stdout;
import 'package:interact/interact.dart' show GridSelect;

void main() {
  final movies = [
    'The Shawshank Redemption',
    'The Godfather',
    'The Dark Knight',
    'The Godfather Part II',
    '12 Angry Men',
    'Schindler\'s List',
    'The Lord of the Rings: The Return of the King',
    'Pulp Fiction',
    'The Lord of the Rings: The Fellowship of the Ring',
    'The Good, the Bad and the Ugly',
    'Forrest Gump',
    'Fight Club',
    'Inception',
    'The Lord of the Rings: The Two Towers',
    'Star Wars: Episode V - The Empire Strikes Back',
    'The Matrix',
    'Goodfellas',
    'One Flew Over the Cuckoo\'s Nest',
    'Seven',
    'Seven Samurai',
    'It\'s a Wonderful Life',
    'The Silence of the Lambs',
    'City of God',
    'Saving Private Ryan',
    'Life Is Beautiful',
    'The Green Mile',
    'Interstellar',
    'Star Wars',
    'Terminator 2: Judgment Day',
    'Back to the Future',
    'Spirited Away',
    'Psycho',
    'The Pianist',
    'Leon',
    'Parasite',
    'The Lion King',
    'Gladiator',
    'American History X',
    'The Usual Suspects',
    'The Departed',
    'The Prestige',
    'Casablanca',
    'Top Gun: Maverick',
    'Whiplash',
    'Untouchable',
    'Modern Times',
    'Harakiri',
    'Once Upon a Time in the West',
    'Grave of the Fireflies',
    'Rear Window',
    'Alien',
    'City Lights',
    'Cinema Paradiso',
    'Memento',
    'Apocalypse Now',
    'Raiders of the Lost Ark',
    'Django Unchained',
    'WALL·E',
    'The Lives of Others',
    'Sunset Blvd',
    'Paths of Glory',
    'The Shining',
    'The Great Dictator',
    'Witness for the Prosecution',
    'Avengers: Infinity War',
    'Aliens',
    'American Beauty',
    'Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb',
    'The Dark Knight Rises',
    'Spider-Man: Into the Spider-Verse',
    'Joker',
    'Oldboy',
    'Braveheart',
    'Amadeus',
    'Toy Story',
    'Coco',
    'Das Boot',
    'Inglourious Basterds',
    'Princess Mononoke',
    'Once Upon a Time in America',
    'Avengers: Endgame',
    'Good Will Hunting',
    'Requiem for a Dream',
    'Toy Story 3',
    'Your Name',
    'Singin in the Rain',
    '3 Idiots',
    'Star Wars: Return of the Jedi',
    '2001: A Space Odyssey',
    'Reservoir Dogs',
    'Eternal Sunshine of the Spotless Mind',
    'High and Low',
    'Capernaum',
    'Citizen Kane',
    'Lawrence of Arabia',
    'The Hunt',
    'M',
    'North by Northwest',
    'Vertigo',
    'Amélie'
  ];

  final x = GridSelect(
    prompt: 'Let me know your favorite movies',
    options: movies,
  ).interact();

  if (x.isEmpty) {
    stdout.writeln("Oh, you're not a movie fan.");
  } else {
    stdout.writeln(
      '${x.map((i) => movies[i]).join(' and ')} '
      '${x.length == 1 ? 'is' : 'are'} the best!',
    );
  }
}
